
name: Auto Assign Reviewer

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  assign_reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Assign a specific reviewer
        uses: hkusu/review-assign-action@v1
        with:
          reviewers: thepeacemonk   # for peace to be main reviewer