name: Release Ankimon Add-on

on:
  push:
    tags:
      - 'v*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate  # Use 'venv\Scripts\activate' on Windows
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Ankimon add-on
        run: |
          source venv/bin/activate  # Use 'venv\Scripts\activate' on Windows
          python setup.py sdist bdist_wheel
          mkdir -p build
          cp dist/ankimon-1.29-anki21-ankiweb.ankiaddon build/
        id: vars

      - name: Create GitHub release and upload .ankiaddon file
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ankimon-1.29-anki21-ankiweb.ankiaddon
          tag: ${{ github.ref }}
          release_name: Ankimon v${{ github.ref }}
